// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmXm9t99lF5QVDL59XlglODjqUV0SHBvo',
    appId: '1:145013330703:web:c41b3e91047dbf8f59647a',
    messagingSenderId: '145013330703',
    projectId: 'urun-fiyat-listesi',
    authDomain: 'urun-fiyat-listesi.firebaseapp.com',
    storageBucket: 'urun-fiyat-listesi.appspot.com',
    measurementId: 'G-HTBTDG4CCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUntf-kOaCq5YV-QJCQucex4CY6uESDkU',
    appId: '1:145013330703:android:e1b424fbb63e3cef59647a',
    messagingSenderId: '145013330703',
    projectId: 'urun-fiyat-listesi',
    storageBucket: 'urun-fiyat-listesi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_t1cQBf5t-1F1-9w1mkB-oAWGfG9QWLU',
    appId: '1:145013330703:ios:e5a4134b76d558e559647a',
    messagingSenderId: '145013330703',
    projectId: 'urun-fiyat-listesi',
    storageBucket: 'urun-fiyat-listesi.appspot.com',
    iosBundleId: 'com.example.urunFiyat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_t1cQBf5t-1F1-9w1mkB-oAWGfG9QWLU',
    appId: '1:145013330703:ios:e5a4134b76d558e559647a',
    messagingSenderId: '145013330703',
    projectId: 'urun-fiyat-listesi',
    storageBucket: 'urun-fiyat-listesi.appspot.com',
    iosBundleId: 'com.example.urunFiyat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmXm9t99lF5QVDL59XlglODjqUV0SHBvo',
    appId: '1:145013330703:web:7c9434ef45ea3a4259647a',
    messagingSenderId: '145013330703',
    projectId: 'urun-fiyat-listesi',
    authDomain: 'urun-fiyat-listesi.firebaseapp.com',
    storageBucket: 'urun-fiyat-listesi.appspot.com',
    measurementId: 'G-KJDE9954MD',
  );
}
